version: '3.8'

services:
  db:
    image: postgres:17
    container_name: social_db
    environment:
      POSTGRES_DB: service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: social_app
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/service
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    depends_on:
      - db

volumes:
  postgres_data:
